server:
  port: 8090

zookeeper: 127.0.0.1:2181

frpc:
  application:
    name: frpc-provider
  repository:
    type: zookeeper
    address: zookeeper://${zookeeper}
  provider:
    host: 127.0.0.1
    port: 8090
    contextPath: /provider