server:
  port: 8089

zookeeper: 127.0.0.1:2181

frpc:
  application:
    name: mall-provider
  registry:
    address: zookeeper://${zookeeper}
  provider:
    host: 127.0.0.1
    port: 8089
    contextPath: /provider